function debug_export_motorPosition_EI_table_for_julia(inputFile, outputCsv)
%DEBUG_EXPORT_MOTORPOSITION_EI_TABLE_FOR_JULIA
% Export the opaque MATLAB motor-position/EI sweep table into a plain numeric
% CSV that the Julia migration script can consume.

if nargin < 1 || isempty(inputFile)
    error('inputFile is required.');
end
if nargin < 2 || isempty(outputCsv)
    error('outputCsv is required.');
end

data = load(inputFile);
names = fieldnames(data);
if isempty(names)
    error('No variables found in %s.', inputFile);
end

T = data.(names{1});
if ~istable(T)
    error('Expected a table in %s, got %s.', inputFile, class(T));
end

args = T.args;
power = arrayfun(@(a) a.power, args);
thrust = arrayfun(@(a) a.thrust, args);

out = table( ...
    T.EI, ...
    T.motor_position, ...
    T.tail_flat_ratio, ...
    T.eta_beam_ratio, ...
    T.eta_edge_ratio, ...
    real(T.eta_left_beam), ...
    imag(T.eta_left_beam), ...
    real(T.eta_right_beam), ...
    imag(T.eta_right_beam), ...
    real(T.eta_left_domain), ...
    imag(T.eta_left_domain), ...
    real(T.eta_right_domain), ...
    imag(T.eta_right_domain), ...
    power, ...
    thrust, ...
    double(T.success), ...
    double(T.retries), ...
    T.Sxx, ...
    T.N_x, ...
    T.M_z, ...
    T.n_used, ...
    T.M_used, ...
    'VariableNames', { ...
        'EI', ...
        'motor_position', ...
        'tail_flat_ratio', ...
        'eta_beam_ratio', ...
        'eta_edge_ratio', ...
        'eta_left_beam_re', ...
        'eta_left_beam_im', ...
        'eta_right_beam_re', ...
        'eta_right_beam_im', ...
        'eta_left_domain_re', ...
        'eta_left_domain_im', ...
        'eta_right_domain_re', ...
        'eta_right_domain_im', ...
        'power', ...
        'thrust', ...
        'success', ...
        'retries', ...
        'Sxx', ...
        'N_x', ...
        'M_z', ...
        'n_used', ...
        'M_used'});

writetable(out, outputCsv);
fprintf('Saved %s\n', outputCsv);

end
