function debug_parity_reference_case_cli
% Headless MATLAB reference case for Julia parity checks.
% Writes a single CSV line to the path in SURFERBOT_PARITY_OUTPUT:
% U,power,thrust

outPath = getenv('SURFERBOT_PARITY_OUTPUT');
if isempty(outPath)
    error('SURFERBOT_PARITY_OUTPUT is not set.');
end

[U, ~, ~, ~, ~, args] = flexible_surferbot_v2( ...
    'sigma', 0.0, ...
    'rho', 1000.0, ...
    'nu', 1e-6, ...
    'g', 10 * 9.81, ...
    'L_raft', 0.1, ...
    'motor_position', 0.5 * 0.1 / 2, ...
    'd', 0.1 / 2, ...
    'EI', 100 * 3.0e9 * 3e-2 * (9.9e-4)^3 / 12, ...
    'rho_raft', 0.018 * 3.0, ...
    'domainDepth', 0.2, ...
    'n', 41, ...
    'M', 30, ...
    'motor_inertia', 0.13e-3 * 2.5e-3, ...
    'BC', 'radiative', ...
    'omega', 2 * pi * 10);

fid = fopen(outPath, 'w');
if fid < 0
    error('Could not open output file: %s', outPath);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%.17g,%.17g,%.17g\n', U, args.power, args.thrust);
end
