function metrics = extract_eta_edge_metrics(eta, args)
%EXTRACT_ETA_EDGE_METRICS Collect domain-edge and beam-edge eta metrics.
%   METRICS = EXTRACT_ETA_EDGE_METRICS(ETA, ARGS) returns the left/right
%   free-surface amplitudes at the computational-domain edges and at the
%   beam ends. Beam ends are defined by the first and last true entries of
%   ARGS.x_contact, matching the raft-contact region used in the solver.

eta = eta(:);
x_contact = logical(args.x_contact(:));

left_beam_idx = find(x_contact, 1, 'first');
right_beam_idx = find(x_contact, 1, 'last');

assert(~isempty(left_beam_idx) && ~isempty(right_beam_idx), ...
    'extract_eta_edge_metrics:NoBeamContact', ...
    'args.x_contact must contain at least one raft-contact node.');

eta_left_domain = eta(1);
eta_right_domain = eta(end);
eta_left_beam = eta(left_beam_idx);
eta_right_beam = eta(right_beam_idx);

metrics = struct( ...
    'eta_left_domain', eta_left_domain, ...
    'eta_right_domain', eta_right_domain, ...
    'eta_left_beam', eta_left_beam, ...
    'eta_right_beam', eta_right_beam, ...
    'eta_domain_ratio', abs(eta_left_domain) / max(eps, abs(eta_right_domain)), ...
    'eta_beam_ratio', abs(eta_left_beam) / max(eps, abs(eta_right_beam)), ...
    'left_beam_idx', left_beam_idx, ...
    'right_beam_idx', right_beam_idx);

