function S = thrust_vs_Ldomain_test
% L-domain study: vary L_domain, plot |eta(x)| per case and thrust vs L_domain

addpath('../src');

L_raft = 0.05;
base = struct( ...
    'sigma',0, 'rho',1000, 'nu',0, 'g',9.81, ...
    'L_raft',L_raft, 'L_domain', 0.50, ...          % <-- base horizontal domain length [m]
    'motor_position',0.3*L_raft/2, 'd',L_raft/2, ...
    'EI',100*3.0e9*3e-2*(9.9e-4)^3/12, 'rho_raft',0.018*3.0, ...
    'domainDepth',0.5, 'n',51, 'M',50, ...
    'motor_inertia',0.13e-3*2.5e-3, 'BC','radiative', ...
    'omega',2*pi*5, 'ooa', 4);


% L_domain values to test
L_list = base.L_domain * [0.5, 1, 2, 4];
L_list = unique(L_list,'stable');

% Preallocate
proto = struct('x',[],'z',[],'phi',[],'eta',[], ...
               'N_x',0,'M_z',0,'L_domain',0, ...
               'thrust_N',NaN,'tail_flat_ratio',NaN,'disp_res',NaN, ...
               'args', struct());   % was []; must be struct
S = repmat(proto, 1, numel(L_list));


% Run sweep
for i = 1:numel(L_list)
    p = base; p.L_domain = L_list(i);
    S(i) = run_case(p);
end

% Plot |eta(x)| per case
A = S(1).args;

figure(1); clf;
set(gcf,'Units','pixels','Position',[80 80 1200 500]);  % wide

% left plot (~75% width)
ax = axes('Position',[0.07 0.12 0.68 0.80]); hold(ax,'on');
for i = 1:numel(S)
    semilogy(ax, S(i).x, abs(S(i).eta), ...
        'DisplayName', sprintf('L=%.3g m', S(i).L_domain));
end
xlabel(ax,'x (m)'); ylabel(ax,'|{\eta}(x)|');
legend(ax,'show','Location','best'); grid(ax,'on'); set(ax,'FontSize',14);
title(ax, sprintf('Free-surface amplitude vs x  (k\\cdotdx = %.2g)', A.k*A.dx));  % prefer k*dx

% right log panel
info = sprintf([ ...
    'k*dx = %.3g\n' ...
    'dz/H = %.3g\n' ...
    'omega = %.3g 1/s\n' ...
    'L_raft = %.3g m\n' ...
    'L_{domain} = %.3g m\n' ...
    'H = %.3g m\n' ...
    'd = %.3g m\n' ...
    'EI = %.3g\n' ...
    'Gamma = %.3g\n' ...
    'Fr = %.3g\n' ...
    'kappa = %.3g\n' ...
    'Lambda = %.3g'], ...
    A.k*A.dx, A.dz/A.domainDepth, ...
    A.omega, A.L_raft, A.L_domain, A.domainDepth, ...
    A.d, A.EI, ...
    A.nd_groups.Gamma, A.nd_groups.Fr, A.nd_groups.kappa, ...
    A.nd_groups.Lambda);

annotation('textbox',[0.78 0.12 0.20 0.80], ...
    'String', sprintf('Run constants\n\n%s', info), ...
    'Interpreter','none','EdgeColor','none', ...
    'VerticalAlignment','top','FontSize',16,'FontName','FixedWidth');


% Plot thrust vs L_domain
figure(2); clf;
plot([S.L_domain], [S.thrust_N], 'o-','MarkerSize',6,'LineWidth',1.2);
xlabel('L\_domain (m)'); ylabel('Thrust (N)');
set(gca,'FontSize',14);
title('Thrust vs L\_domain');

% Console table
T = table([S.L_domain].', [S.N_x].', [S.M_z].', ...
          [S.thrust_N].', [S.tail_flat_ratio].', [S.disp_res].', ...
    'VariableNames', {'L_domain_m','N_x','M_z','thrust_N','tail_flat_ratio','dispersion_resid'});
disp('=== L_domain sweep results ==='); disp(T);

end

% ---- helpers ----
function S = run_case(p)
% Pass L_domain through to the solver (solver must honor it)
[~, x, z, phi, eta, args] = flexible_surferbot_v2( ...
    'sigma',p.sigma,'rho',p.rho,'omega',p.omega,'nu',p.nu,'g',p.g, ...
    'L_raft',p.L_raft,'L_domain',p.L_domain, ...
    'motor_position',p.motor_position,'d',p.d, ...
    'EI',p.EI,'rho_raft',p.rho_raft,'domainDepth',p.domainDepth, ...
    'n',p.n,'M',p.M,'motor_inertia',p.motor_inertia,'BC',p.BC);

% Diagnostics
k   = real(args.k);
H   = p.domainDepth;
res = abs(args.omega^2 - args.g*k*tanh(k*H));   % finite-depth dispersion residual

% Optional interior-tail flatness metric
idx0 = max(1, ceil(0.75*numel(eta)));
tail = abs(eta(idx0:end));
tail_ratio = std(tail) / max(eps, mean(tail));

S = struct('x',x,'z',z,'phi',phi,'eta',eta, ...
           'N_x',args.N,'M_z',args.M, ...
           'L_domain',p.L_domain, ...
           'thrust_N',args.thrust, ...
           'tail_flat_ratio',tail_ratio, ...
           'args', args, ...
           'disp_res',res);
end
