% regenerate_manifest.m
output_csv = 'surferbot_results/manifest.csv';
folders = dir('surferbot_results/');
folders = folders([folders.isdir] & ~startsWith({folders.name}, '.'));

fid = fopen(output_csv, 'w');
fprintf(fid, "run_id,U_m,f_hz,EI_Nm2,motor_pos_m,motor_inertia_kgm,domain_depth_m,L_raft_m,n,M,BC\n");

for k = 1:numel(folders)
    folder = fullfile(folders(k).folder, folders(k).name);
    json_file = fullfile(folder, 'config.json');
    result_file = fullfile(folder, 'results.mat');
    
    if exist(json_file, 'file') && exist(result_file, 'file')
        args = jsondecode(fileread(json_file));
        S = load(result_file, 'U');
        U = S.U;

        fprintf(fid, "%s,%.6g,%.6g,%.6g,%.6g,%.6g,%.6g,%.6g,%d,%d,%s\n", ...
            strtrim(folders(k).name), ...
            U, ...
            args.omega/(2*pi), ...
            args.EI, ...
            args.motor_position, ...
            args.motor_inertia, ...
            args.domainDepth, ...
            args.L_raft, ...
            args.n, ...
            args.M, ...
            args.BC);
    end
end

fclose(fid);
fprintf('Manifest regenerated at %s\n', output_csv);
